apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: chainsaw-app-project
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: chainsaw-app-project
  destinations:
    - name: '*'
      namespace: '*'
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chainsaw-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/example/repo.git
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chainsaw-applicationset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://gitlab.com/codewayco/devops/internal-development/playground.git
      revision: HEAD
  template:
    metadata:
      name: 'chainsaw-test'
    spec:
      project: default
      source:
        repoURL: https://github.com/example/repo.git
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
